### ISSUE TITLE
Embracing Bootstrap: Revitalizing blog project

### ISSUE THREAD

**Issue by Qodestackr** [jebitok-dev/1-Jebitok-techincal-writing-blog#1]
Let's compose a masterpiece that surpasses all expectations and resonates with the hearts and minds of our readers.

I believe you wanna build a personal blog. 
I propose, a stack:
- Next.js 
Next.js is a powerful framework that blends server-side rendering and static site generation seamlessly. With Next.js, we'll create a performant and dynamic blog that captivates our readers. TypeScript scales enough, our guiding melody for quality and confidence in every keystroke.. :rofl: 

Prisma for data/postgres

**Comment by jebitok-dev** [comment]
Do you want to collaborate, it was for the Hashnode pipeline.
